
#' Turn cluster labels from 'hard' clustering algorithm into an allocation probability matrix
#'
#' `hard_to_prob_fn()` is used to generate a matrix of probabilities (1 or 0) of allocation to clusters, based on a list of cluster labels generated by a 'hard' clustering algorithm (binary/non-probabilistic allocation)
#'
#' @param hard_clusters A vector of cluster allocations from a hard clustering algorithm of length N (number of observations in clustered dataset)
#' @param n_clust The number of clusters, k, in the clustering solution
#'
#' @return Returns a N x k matrix of cluster allocation probabilities, which is used as an input for `clusterBMA::clusterBMA()`
#' @export
#'
#'
hard_to_prob_fn <- function(hard_clusters,n_clust){
  prob_mat <- matrix(0,nrow=length(hard_clusters),ncol=n_clust)
  for(i in 1:length(hard_clusters)){
    prob_mat[i,hard_clusters[i]] <- 1
  }
  prob_mat
}
